{ config, pkgs, ... }:

{
  # Import External Configurations
  # These files contain additional configurations and settings.
  imports = [
    ./hardware-configuration.nix # System hardware settings (auto-generated by nixos-generate-config)
    ./c0d3h01 # User-specific configuration (e.g., dotfiles, personal tweaks)
    ./dev # Development tools and settings (e.g., editors, compilers)
    ./amd # AMD-specific settings (e.g., GPU drivers, performance tweaks)
  ];

  # System Configuration
  # The system state version determines compatibility with older versions of NixOS.
  # Change this only when upgrading your system manually.
  system.stateVersion = "24.11";

  # Set the hostname of the system (used for networking and system identification).
  networking.hostName = "NixOS";

  # Bootloader Configuration
  # This section configures the system bootloader.
  boot.loader = {
    systemd-boot.enable = true; # Enable systemd-boot (UEFI boot manager)
    efi.canTouchEfiVariables = true; # Allow modifying EFI variables (needed for UEFI booting)
  };

  # Environment Variables
  # These variables are set for all user sessions and influence system behavior.
  environment.sessionVariables = {
    NIXOS_XDG_OPEN_USE_PORTAL = "1"; # Ensures apps use xdg-desktop-portal for opening URLs/files
  };

  # Enabled Programs
  # This section enables important system programs and tools.
  programs = {
    gnupg.agent = {
      enable = true; # Enable GnuPG (GPG) agent for managing encryption keys
      enableSSHSupport = true; # Allow GPG keys to be used for SSH authentication
    };

    zsh.enable = true; # Enable Zsh shell (alternative to Bash)
  };

  # System Services
  services = {
    # Printing Service (CUPS)
    printing.enable = true; # Enables the Common Unix Printing System (CUPS) for printers

    # X11 Window System Configuration
    xserver = {
      enable = true; # Enable the X11 graphical system
      videoDrivers = [ "amdgpu" ]; # Use AMD GPU drivers
      xkb.layout = "us"; # Set the default keyboard layout to US
    };

    # SSH Server Configuration
    openssh.enable = true; # Enable OpenSSH server for remote login access
  };
}
